# -*- coding: utf-8 -*-
"""Simulation Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mGGYsuqToyu0yOhd4hWXl_ziRWjpYFgp
"""

import pandas as pd

"""cara membaca/import file csv"""

salary= pd.read_csv('salary_dataset_2.csv')
salary.info()

"""1. cek duplicate
2. cek data kosong
3. cek data error
4. cek outliers
5. change datatype
"""

salary_backup = salary.copy()

salary

"""1. Drop Duplicates"""

salary[salary.duplicated()]

salary=salary.drop_duplicates()

salary.info()

salary[salary.duplicated()]

"""2. Handle Missing Data"""

salary.isna().sum()

salary = salary[~salary['salary'].isna()]
salary = salary[~salary['salary_in_usd'].isna()]

"""3. Remove irrelevant Data/Column"""

salary = salary.drop('salary', axis=1)
salary = salary.drop('salary_currency', axis=1)
salary

"""4. Replace value (optional)"""

salary['experience_level'] = salary['experience_level'].replace('EN','Junior')
salary['experience_level'] = salary['experience_level'].replace('MI','Intermediate')
salary['experience_level'] = salary['experience_level'].replace('SE','Expert')
salary['experience_level'] = salary['experience_level'].replace('EX','Director')

salary['employment_type'] = salary['employment_type'].replace('FT','Full-Time')
salary['employment_type'] = salary['employment_type'].replace('PT','Part-Time')
salary['employment_type'] = salary['employment_type'].replace('CT','Contract')
salary['employment_type'] = salary['employment_type'].replace('FL','Freelance')

salary['company_size'] = salary['company_size'].replace('S','Small')
salary['company_size'] = salary['company_size'].replace('M','Medium')
salary['company_size'] = salary['company_size'].replace('L','Large')

salary['remote_ratio'] = salary['remote_ratio'].replace(0,'WFO')
salary['remote_ratio'] = salary['remote_ratio'].replace(50,'Hybrid')
salary['remote_ratio'] = salary['remote_ratio'].replace(100,'WFH')

salary['employee_residence'].unique()

salary

"""5. Check Outliers"""

#before
salary.boxplot(column='salary_in_usd')

salary['salary_in_usd'].describe()

"""Batas atas = Q3 + 1.5 X (Q3-Q1),
Batas bawah = Q1 - 1.5 X (Q3-Q1)
"""

q1 = salary['salary_in_usd'].quantile(0.25)
q3 = salary['salary_in_usd'].quantile(0.75)
upper_limit = q3 + (1.5 * (q3-q1))
lower_limit = q1 - (1.5 * (q3-q1))

salary = salary[salary['salary_in_usd'] > lower_limit]
salary = salary[salary['salary_in_usd'] < upper_limit]
salary['salary_in_usd'].describe()

#after
salary.boxplot(column='salary_in_usd')

salary.info()

salary

salary.to_csv('salary_cleaned.csv')

from google.colab import files
files.download('salary_cleaned.csv')